#!/bin/bash

echo test
echo test2
echo test3
echo test4

echo test
echo test2
echo test3
echo test4

echo test
echo test2
echo test3

echo test4
echo test
echo test2
echo test3

echo test4

echo test
echo test2
echo test3

echo test4

echo test
echo test2
echo test3

echo "Test"
echo "1"
echo "2" 

echo test4



